DCM:12: Support Yearly period type in run report
openmrs/openmrs-module-dhisconnector pull request #16
Opened 2020-12-20 15:22 UTC by Bawanthathilan

2020-12-21 03:42 UTC, anjula-sack requested changes

2020-12-21 03:42 UTC, anjula-sack commented on omod/src/main/webapp/runReports.jsp
> +            <input type="text" name="date" id="dailyperiodSelector" class="periodSelector"/>
Use camel case for id. ex: dailyPeriodSelector

2020-12-21 03:42 UTC, anjula-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +            document.getElementById("monthly").style.display = "show";
Can't we show only the div that needs to be shown and stop setting display none for other types everytime

2020-12-21 03:42 UTC, anjula-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +            document.getElementById("datepicker").addEventListener("change", function() {
Move eventListeners to seperate functions

2020-12-21 03:42 UTC, anjula-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +            document.getElementById("daily").style.display = "none";
I think it's better to use jquery to hide and show the divs

2020-12-21 06:06 UTC, anjula-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +                yearRange: '1950:2019',
Do not hard code 2019.

2020-12-21 06:32 UTC, anjula-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +let newSelectedDate;
Change this to selectedDateRange

2020-12-22 14:25 UTC, jayasanka-sack requested changes
Good job @Bawanthathilan! I've added some comments. Fix them and let me know.

Also, please add a gif or a video to demo your work

2020-12-22 14:25 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +    });
Seems we don't need this listener because the yearly input has already linked with `onYearChange()` function

2020-12-22 14:25 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +let selectedDateRange;
How about `selectedPeriod`?

2020-12-22 14:25 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +function hideDiv(){
Let's make this function name more self-explanatory. ex: hidePertiodPickers

2020-12-22 14:25 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> -
Add a new line between functions

2020-12-22 14:25 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
>  function onMappingSelect() {
Add a new line between functions

2020-12-22 14:25 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +function onYearChange() {
Let's rename these listeners with a different naming convention, something like `handleYearChange()`

2020-12-22 14:54 UTC, jayasanka-sack requested changes
Great @Bawanthathilan ! 
I've added some minor comments. 

The demo gif should be something like this:

1. Go to the page
2. Select a mapping with monthly type
3. Pick a value from the picker
4. Change the mapping to mapping with the yearly type (without refreshing)
5. Change the year
6. Change the mapping to mapping with weekly/daily type
7. Pick a value

2020-12-22 14:54 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +    onYearChange();
```suggestion
    handleYearChange();
```

2020-12-22 14:54 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +    //document.getElementById("monthly").style.display = "block";
Remove this comment

2020-12-22 16:31 UTC, jayasanka-sack requested changes
The other places which use the value of period selector also should be changed. 

ex:  buildDXFJSON()  - which builds the request payload to be sent to DHIS2
getReportData()  - Which fetch the report data. 



jQuery('#periodSelector')

2020-12-22 19:03 UTC, Piumal1999 commented on omod/src/main/webapp/resources/dhisconnector-runreports.js
> +function initaialzieMonthlyPicker(){
a small spelling mistake:
```suggestion
function initializeMonthlyPicker(){
```

2020-12-23 20:01 UTC, jayasanka-sack approved these changes
Thanks @Bawanthathilan !

2020-12-23 20:01 UTC, merged