DCM-24: The automation UI allows to add mappings with unsupported period types
openmrs/openmrs-module-dhisconnector pull request #18
Opened 2020-12-22 03:59 UTC by anjula-sack

### The issue I worked on
See https://issues.openmrs.org/browse/DCM-24

### Description of what I changed:
Add an if condition to check the period types

2020-12-22 14:07 UTC, jayasanka-sack requested changes
Thank you very much Anjual! This is awesome!

I've added a comment.

Also, change the PR title and the commit message with what you did.

2020-12-22 14:07 UTC, jayasanka-sack commented on omod/src/main/webapp/automation.jsp
> +                            mapping.periodType == 'Weekly' || mapping.periodType == 'Monthly' || mapping.periodType == 'Yearly'}">
Shall we create an array instead?

2020-12-25 14:23 UTC, anjula-sack commented on omod/src/main/webapp/automation.jsp
> +                            mapping.periodType == 'Weekly' || mapping.periodType == 'Monthly' || mapping.periodType == 'Yearly'}">
I filtered the array in java

2020-12-26 06:47 UTC, jayasanka-sack requested changes
Well done @anjula-sack!

Minor request, Just fix the formattings as suggested. 
Update the commit message too

2020-12-26 06:47 UTC, jayasanka-sack commented on omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
> +				.stream().filter(mapping -> supportedPeriodTypes.contains(mapping.getPeriodType())).collect(Collectors.toList()));
```suggestion
		// add a comment
		List<type> supportedMappings = Context.getService(DHISConnectorService.class).getMappings()
						.stream()
						.filter(mapping -> supportedPeriodTypes.contains(mapping.getPeriodType()))
						.collect(Collectors.toList()));	
		model.addAttribute("mappings", supportedMappings); 
```

Note the formatting.

2020-12-26 06:47 UTC, jayasanka-sack commented on omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
> +				"Financial July", "Financial Oct");
```suggestion
		List<String> supportedPeriodTypes = Arrays.asList(
				"Daily", 
				"Weekly", 
				"Monthly", 
				"yearly", 
				"Financial April",
				"Financial July", 
				"Financial Oct");
```

2020-12-26 06:52 UTC, Piumal1999 commented on omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
> +				"Financial July", "Financial Oct");
`"yearly"` - is this case sensitive?

2020-12-26 10:06 UTC, jayasanka-sack commented on omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
> +		List<String> supportedPeriodTypes = Arrays.asList(
Let's make this a constant vatiable

2020-12-26 10:24 UTC, jayasanka-sack approved these changes
Thanks @anjula-sack !

2020-12-26 10:24 UTC, merged