DCM-73 Improve Run Report UI getting cluttered after pushing data
openmrs/openmrs-module-dhisconnector pull request #62
Opened 2021-10-31 16:50 UTC by 99sumedha

## The issue I worked on 
See: [DCM-73 Run Report UI is getting cluttered after pushing data](https://issues.openmrs.org/browse/DCM-73)

## Description of what I changed: 
Fixed the issues where UI gets cluttered after multiple organization responses are displayed.

2021-11-01 21:48 UTC, HerbertYiga commented on omod/src/main/webapp/resources/dhisconnector.css
> +
you can remove this unwanted space too

2021-11-04 07:25 UTC, 99sumedha commented on omod/src/main/webapp/resources/dhisconnector.css
> +
Sure @HerbertYiga

2021-11-05 15:32 UTC, 99sumedha commented on omod/src/main/webapp/resources/dhisconnector.css
> +
@HerbertYiga Done

2021-11-05 17:00 UTC, Piumal1999 requested changes
Good job @99sumedha 
I requested a minor change

2021-11-05 17:00 UTC, Piumal1999 commented on omod/src/main/webapp/runReports.jsp
> +        <div id="locationsList" class=max-content-size>Select a Mapping to choose the Locations</div>
```suggestion
        <div id="locationsList" class="max-content-size">Select a Mapping to choose the Locations</div>
```

2021-11-08 13:07 UTC, 99sumedha commented
@HerbertYiga @Piumal1999 Is there anything else that I should change?

2021-11-09 08:47 UTC, Piumal1999 approved these changes
Looks good! I think we can merge this. Well done @99sumedha 

cc: @jayasanka-sack

2021-11-21 12:27 UTC, jayasanka-sack requested changes
Thanks @99sumedha !
I requested a small formatting change

2021-11-21 12:27 UTC, jayasanka-sack commented on omod/src/main/webapp/resources/dhisconnector.css
> +}
```suggestion
}

.max-content-size {
    width: max-content;
}
```

2021-11-21 12:36 UTC, jayasanka-sack approved these changes
Thanks for getting this done, @99sumedha !

2021-11-21 12:37 UTC, merged