DCM-80: NullPointerException is thrown in Automation
openmrs/openmrs-module-dhisconnector pull request #63
Opened 2022-03-24 15:58 UTC by kumuditha-udayanga

### The issue I worked on
See: https://issues.openmrs.org/browse/DCM-80

### Description of what I changed:
* Use an if-else condition to filter the NullPointerException.

2022-12-07 15:11 UTC, jayasanka-sack commented
cc: @Gravewalker666

2022-12-07 20:14 UTC, Piumal1999 requested changes
Hi @kumuditha-udayanga, sorry for taking too long to review. 
Requested some minor changes

2022-12-07 20:14 UTC, Piumal1999 commented on omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
>  				.collect(Collectors.toList());
```suggestion
			List<DHISMapping> supportedMappings = mappings
				.stream()
				.filter(mapping -> SUPPORTED_AUTOMATION_PERIOD_TYPES.contains(mapping.getPeriodType()))
				.collect(Collectors.toList());
```

2022-12-07 20:14 UTC, Piumal1999 commented on omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
> +		}
```suggestion
                }
	        model.addAttribute("showLogin", (Context.getAuthenticatedUser() == null) ? true : false);
```

2022-12-07 20:14 UTC, Piumal1999 commented on omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
> +		}
We should add the `showLogin` attribute even if there are no mappings

2025-05-11 13:23 UTC, Piumal1999 commented on omod/src/main/java/org/openmrs/module/dhisconnector/web/controller/DHISConnectorController.java
>  	private void initialiseAutomation(ModelMap model, boolean automationEnabled, List<String> postResponse) {
Let's rearrange the code like this:

```
	private void initialiseAutomation(ModelMap model, boolean automationEnabled, List<String> postResponse) {
		// Filter the mappings with supported period types
		List<DHISMapping> mappings = Context.getService(DHISConnectorService.class).getMappings();
		List<DHISMapping> supportedMappings = mappings == null ?
				new ArrayList<>() :
				mappings.stream()
						.filter(mapping -> SUPPORTED_AUTOMATION_PERIOD_TYPES.contains(mapping.getPeriodType()))
						.collect(Collectors.toList());

		model.addAttribute("mappings", supportedMappings);
		model.addAttribute("reportToDataSetMappings", Context.getService(DHISConnectorService.class).getAllReportToDataSetMappings());
		model.addAttribute("automationEnabled", automationEnabled);
		model.addAttribute("postResponse", postResponse);
		model.addAttribute("showLogin", (Context.getAuthenticatedUser() == null) ? true : false);
	}
```

2025-07-05 08:53 UTC, kumuditha-udayanga commented
@Piumal1999 Pushed the changes by rearranging the code as requested, sorry for the delay

2025-07-08 01:59 UTC, Piumal1999 approved these changes
Thank you @kumuditha-udayanga

2025-07-08 02:00 UTC, merged